server:
  port: 8080
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka
    instance:
      hostname: localhost

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: usuario-service
          uri: lb://usuario-service
          predicates:
            - Path=/usuario/**
        - id: cuaderno-service
          uri: lb://cuaderno-service
          predicates:
            - Path=/cuaderno/**
        - id: libro-service
          uri: lb://libro-service
          predicates:
            - Path=/libro/**