server:
  port: 8090
spring:
  cloud:
    config:
      server:
        git:
          default-label: circuit-breaker
          uri: https://github.com/Brandon18092003/microservicios_materiales
          search-paths: config-data
  application:
    name: config-service